const events = {
  SET_LOCATION_PARAMS: 'SET_LOCATION_PARAMS',
  SET_DRAWING_MODE: 'SET_DRAWING_MODE',
  CREATE_AREA_OBJECT: 'CREATE_AREA_OBJECT',
  UPDATE_AREA_OBJECTS: 'UPDATE_AREA_OBJECTS',
  REMOVE_AREA_OBJECTS: 'REMOVE_AREA_OBJECTS'
};

export default events;
