const events = {
  SET_MISSION_PARAMS: 'SET_MISSION_PARAMS',
  CHANGE_SCOUT_GROUP_ROLE: 'CHANGE_SCOUT_GROUP_ROLE',
  CHANGE_STRIKE_GROUP_ROLE: 'CHANGE_STRIKE_GROUP_ROLE',
  SET_UNIT_GROUP: 'SET_UNIT_GROUP',
  SET_MAP_POINT: 'SET_MAP_POINT',
  SET_MAP_POINT_MODE: 'SET_MAP_POINT_MODE',
  SET_DRAWING_MODE: 'SET_DRAWING_MODE',
  CREATE_AREA_OBJECT: 'CREATE_AREA_OBJECT',
  UPDATE_AREA_OBJECTS: 'UPDATE_AREA_OBJECTS',
  REMOVE_AREA_OBJECTS: 'REMOVE_AREA_OBJECTS'
};

export default events;
